package com.ryanberdeen.routes.path;

import java.util.Map;
import java.util.regex.Matcher;


public interface PathSegment {
	/** Appends the regex that represents this segment to the builder.
	 */
	public void appendRegex(StringBuilder regexBuilder);

	/** Appends the path generated by applying the parameters to this segment to the builder.
	 */
	public void appendPath(PathBuilder pathBuilder, Map<String, Object> parameters, Map<String, String> staticParameters, Map<String, String> contextParameters);

	/** Appends the template that represents this segment to the builder.
	 */
	public void appendTemplate(StringBuilder templateBuilder);

	/**
	 * Consumes groups matched in the path regular expression.
	 * @param matcher the matcher that matched the path
	 * @param group the index of the first group this segment may consume
	 * @param parameters the parameters resulting from the path match
	 * @return the number of groups consumed
	 */
	public int consumeMatch(Matcher matcher, int group, Map<String, String> parameters);
}